### PR TITLE
Basecamp4!

### PR DESCRIPTION
**Pull request by intrip**
/cc @basecamp/sip

### CODE REVIEW

**Comment by rvanbaalen** [comment]
Exciting news! Are there any significant (breaking?) API changes between BC3 and BC4?

**Comment by intrip** [comment]
No breaking changes in our API were introduced with the upgrade to BC4.

**Comment by rvanbaalen** [comment]
That's great news! I've followed your PR's and commits over the last few days. Will there be some sort of summary of new features in the BC4 API?

**Comment by intrip** [comment]
I'm not sure yet if we'll do a post for the new feature on the BC4 API.
The new biggest addition is the Card table API:

[Card table cards](https://github.com/basecamp/bc3-api/blob/master/sections/card_table_cards.md#card-table-cards)
[Card table columns](https://github.com/basecamp/bc3-api/blob/master/sections/card_table_columns.md#card-table-columns)
[Card tables](https://github.com/basecamp/bc3-api/blob/master/sections/card_tables.md#card-tables)

**Pull request merged**
